config_dir: "$HOME/.ai-commons"
node_state_file_path: "$HOME/.ai-commons/node_state.yaml"

logging:
  file: ""
  level: INFO
  json: false
  stdout: true
ssh:
  hostname: "aspire2antu.nscc.sg"
  config_path: "$HOME/.ai-commons/ssh_config"
  keys_path: "$HOME/.ssh"
  known_hosts_path: "$HOME/.ai-commons/known_hosts"
  key_prefix: "nscc_"
  max_attempts: 3
  sleep_seconds: 5
  timeout_seconds: 30
bitwarden:
  api_url: "https://api.bitwarden.eu"
  identity_url: "https://identity.bitwarden.eu"
  state_file: "$HOME/.ai-commons/state"

experiments:
  - name: "slimsc"
    git_required: false
    nodes:
      # - host: silv0011
      #   # cluster: nscc
      #   experiment_config_paths:
      #     - src: "experiments.yaml"
      #       dest: "experiments.yaml"
      #       command: bash -eu .ai-commons/setup/run_slimsc.sh /experiments/experiments.yaml
      #   # TODO: add a way to override setup config per node
      - host: mohdlami
        # cluster: 4ir
        experiment_config_paths:
          - src: "experiments.yaml"
            dest: "experiments.yaml"
            command: bash -eu .ai-commons/setup/run_slimsc.sh /experiments/experiments.yaml
    # experiment config directory
    local_config_dir: "example/slimsc"
    remote_config_dir: "/scratch/users/ntu/$USER/.ai-commons/experiments/slimsc"
    cmd_dir: "/scratch/users/ntu/$USER"

    # setup and clean up scripts
    setup:
      setup_files_dir: "/scratch/users/ntu/$USER/.ai-commons/setup"
      setup_script_local_path: "example/slimsc/setup.sh"
      setup_script_remote_path: "setup.sh"
      # setup_args: # TODO: add arguments for setup script
      #   - "--refresh-sif"
      setup_files:
        # files used in the setup script
        - src: "example/pbs/download_r1.pbs"
          dest: "download_r1.pbs"
        - src: "example/slimsc/pull_slimsc_sif.pbs"
          dest: "pull_slimsc_sif.pbs"
        - src: "example/slimsc/pull_vllm_sif.pbs"
          dest: "pull_vllm_sif.pbs"
        - src: "example/secret/dockerhub.env"
          dest: "dockerhub.env"
        # files used to run the experiment
        - src: "example/slimsc/run_slimsc.sh"
          dest: "run_slimsc.sh"
        - src: "example/secret/secret.env"
          dest: "secret.env"

    # cleanup not implemented yet
    cleanup:
      cleanup_script: "example/cleanup.sh"
      cleanup_script_remote_path: "cleanup.sh"
