cache_dir: "$PWD/.cache"
nscc_usage_cache_file_path: "$PWD/.cache/nscc_usage.csv"
node_state_file: "$PWD/.cache/nodes_state.yaml"
logging:
  file: ""
  level: INFO
  json: false
  stdout: true
ssh:
  hostname: "aspire2antu.nscc.sg"
  master_host: "silv0011"
  config_path: "$PWD/.cache/ssh_config"
  keys_path: "$HOME/.ssh"
  known_hosts_path: "$PWD/.cache/known_hosts"
bitwarden:
  api_url: "https://api.bitwarden.eu"
  identity_url: "https://identity.bitwarden.eu"
  state_file: "$PWD/.cache/state"
jobs:
  - name: "slimsc"
    num_jobs_per_node: 2
    nodes: ["silv0011", "collinhon"]
    local_config_dir: "../slimsc/prune/jobs"
    remote_config_dir: "/scratch/users/ntu/$USER/slimsc/prune/jobs"
    experiment_configs: 
      - src: "experiments.yaml"
        dest: "experiments.yaml"
      - src: "experiments_2.yaml"
        dest: "experiments1.yaml"
      - src: "experiments_3.yaml"
        dest: "experiments.yaml"
      - src: "experiments_4.yaml"
        dest: "experiments1.yaml"
    cmd_dir: "/scratch/users/ntu/$USER/slimsc/prune"
    # command: "python jobs/submit_jobs.py --config jobs/experiments.yaml"
    command: "echo \"Hello World!\""
    setup_script: "setup.sh"
    remote_setup_script: "/scratch/users/ntu/$USER/setup.sh"
nscc:
  copy_dir: "/scratch/users/ntu/$USER"
  sif_images_dir: "/scratch/users/ntu/$USER/sif_images"
  result_dir: "/scratch/users/ntu/$USER/results"
  model:
    dir: "/scratch/users/ntu/$USER/models"
    name: "R1-Distill-Qwen-14B"
    source: "hf"
  required_modules:
    - "python/3.10.9"
    - "git"
    - "singularity"
  envs:
    - key: "SINGULARITY_CACHEDIR"
      value: "/scratch/users/ntu/$USER/.singularity"
    - key: "HF_HUB_ENABLE_HF_TRANSFER"
      value: "1"
