cache_dir: "$PWD/.cache"
nscc_usage_cache_file_path: "$PWD/.cache/nscc_usage.csv"
node_state_file: "$PWD/.cache/nodes_state.yaml"
logging:
  file: ""
  level: INFO
  json: false
  stdout: true
ssh:
  hostname: "aspire2antu.nscc.sg"
  master_host: "silv0011" # Master node ?
  config_path: "$PWD/.cache/ssh_config"
  keys_path: "$HOME/.ssh"
  known_hosts_path: "$PWD/.cache/known_hosts"
bitwarden:
  api_url: "https://api.bitwarden.eu"
  identity_url: "https://identity.bitwarden.eu"
  state_file: "$PWD/.cache/state"
experiments:
  - name: "slimsc"
    nodes:
      - host: silv0011
        experiment_config_paths:
          - src: "experiments.yaml"
            dest: "experiments_1.yaml"
            command: "echo \"Hello World!\""
            # command: "python jobs/submit_jobs.py --config jobs/experiments_1.yaml"
          - src: "experiments1.yaml"
            dest: "experiments_2.yaml"
            command: "echo \"Hello World!\""
            # command: "python jobs/submit_jobs.py --config jobs/experiments_2.yaml"
    local_config_dir: "../slimsc/prune/jobs"
    remote_config_dir: "/scratch/users/ntu/$USER/slimsc/prune/jobs"
    cmd_dir: "/scratch/users/ntu/$USER/slimsc/prune"

    # setup and clean up scripts
    env_dir: "/scratch/users/ntu/$USER/env"
    setup:
      setup_script_local_path: "env/setup.sh"
      setup_script_remote_path: "setup.sh"
      setup_files:
        - src: "env/environment.yml"
          dest: "environment.yml"
    cleanup:
      cleanup_script: "env/cleanup.sh"
      cleanup_script_remote_path: "cleanup.sh"
nscc:
  required_modules:
    - "python/3.10.9"
    - "git"
    - "singularity"
  secret:
    - path: ".env"
