#!/bin/bash
#PBS -l select=1:ngpus=1
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -N download_r1_distill
#PBS -o ./logs/download_r1_distill.log
#PBS -W block=true

# check if the model directory exists
if [ -d "/scratch/users/ntu/$USER/models/r1-distill" ]; then
    echo "Model directory already exists, skipping download."
    exit 0
fi

export CUDA_VISIBLE_DEVICES=0
module load singularity
module load cuda
singularity exec --nv \
  -B /scratch/users/ntu/$USER/models:/models \
  /scratch/users/ntu/$USER/sif_images/vllm.sif \
  huggingface-cli download \
  deepseek-ai/DeepSeek-R1-Distill-Qwen-14B \
  --local-dir /models/r1-distill