#!/bin/bash
#PBS -l select=1:ngpus=2
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -N serve_r1_distill
#PBS -o ./logs/serve_r1_distill.log

export CUDA_VISIBLE_DEVICES=0,1
# export HF_HOME=$HOME/scratch/.cache/huggingface
export HF_HOME=$HOME/.cache/huggingface
export SCRATCH_DIR=/scratch/users/ntu/$USER
module load singularity
module load cuda
singularity run \
  --nv \
  -B $SCRATCH_DIR/models:/models \
  $SCRATCH_DIR/sif_images/vllm.sif \
  python3 -m vllm.entrypoints.openai.api_server \
  --model /models/r1_distill
  --tensor-parallel-size 2
