config_dir: /app/.ai-commons
node_state_file_path: /app/.ai-commons/node_state.yaml

ssh:
  hostname: "aspire2antu.nscc.sg"
  config_path: "/app/.ai-commons/ssh_config"
  keys_path: "/app/.ssh"
  known_hosts_path: "/app/.ai-commons/known_hosts"
  key_prefix: "nscc_"
  max_attempts: 3
  sleep_seconds: 5
  timeout_seconds: 30
  port: 22
bitwarden:
  state_file: "/app/.ai-commons/state"
