#!/bin/bash
#PBS -l select=1:ncpus=16:mem=32gb
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -N download_r1_distill
#PBS -o ./logs/download_r1_distill.log
#PBS -W block=true

scratch=/scratch/users/ntu/$USER

# check if the model directory exists
if [ -d "$scratch/models/r1-distill" ]; then
    echo "Model directory already exists, skipping download."
    exit 0
fi

mkdir -p $scratch/models
export CUDA_VISIBLE_DEVICES=0
module load singularity
module load cuda
singularity exec --nv \
  -B $scratch/models:/models \
  /scratch/users/ntu/$USER/sif_images/vllm.sif \
  huggingface-cli download \
  deepseek-ai/DeepSeek-R1-Distill-Qwen-14B \
  --local-dir /models/r1-distill