jobs:
  - name_prefix: "test_batch_size_long_init_gdev" # Unique name for this experiment run
    model_path: "/scratch/users/ntu/$USER/models/r1-distill"
    server:
      sif_path: "/scratch/users/ntu/$USER/sif_images/vllm.sif"
      tensor_parallel_size: 2
      hours: 1
      enable_reasoning: true
      reasoning_parser: "deepseek_r1"
    client:
      gpus: 1
      initial_delay_minutes: 1
      sif_path: "/scratch/users/ntu/$USER/sif_images/slimsc.sif"
    eval:
      type: "similarity"
      n_start: 2
      threshold: 0.60
      pruning_strategy: "fewest_thoughts"
      model_name: "R1-Distill-Qwen-14B" # Unique name for outputs
      model_identifier: "/scratch/users/ntu/$USER/models/r1-distill"
      tokenizer_path: "/scratch/users/ntu/$USER/models/r1-distill"
      output_dir: "/scratch/users/ntu/$USER/slimsc_results"
      logs_dir: "/scratch/users/ntu/$USER/slimsc_logs"
      hf_home: "/scratch/users/ntu/$USER/.cache/huggingface"
      secret_path: "/scratch/users/ntu/$USER/.ai-commons/setup/secret.env"
      dataset_name: "gpqa_diamond"
      num_qns: 2
